### PR TITLE
Config with pure python

### PR DESCRIPTION
**Pull request by icemac**
Run the tests on GHA.

~~Locally on MacOS they fail miserably. But maybe #10 could help here.~~

### CODE REVIEW

**Comment by icemac** [comment]
Rebased after #10 was merged to `master`.

**Comment by icemac** [comment]
Interestingly the tests against ZODB 4 run fine.
@navytux Do you think you are able to also fix the remaining broken tests?

**Comment by navytux** [comment]
@icemac, thanks for asking. I believe yes: please have a look at https://github.com/zopefoundation/zc.zlibstorage/pull/13.

**Comment by navytux** [comment]
@icemac, this PR looks ok to me.
Thanks for caring about zc.zlibstorage state.

**Review by navytux — APPROVED** [review]

**Pull request merged**
